### ISSUE TITLE
Make $config['base_url']  dynamic

### ISSUE THREAD

**Issue by samuelguebo** [arnoldkouya/Codeginiter-with-Bootstrap-MaterialDesign#1]
By default $config['base_url'] is static check /application/config/config.php > line 20 

Make it dynamic this way.

$config['base_url'] =  ((isset($_SERVER['HTTPS']) && $_SERVER['HTTPS'] == "on") ?  "https" : "http");
$config['base_url'] .=  "://".$_SERVER['HTTP_HOST'];
$config['base_url'] .=  str_replace(basename($_SERVER['SCRIPT_NAME']),"",$_SERVER['SCRIPT_NAME']);

**Comment by arnoldkouya** [comment]
Okey,i will fixed it ;)
